Dados numéricos

In [35]:
import pandas as pd
import numpy as np

In [36]:
path = 'dados/dados_hospedagem.json'

dados = pd.read_json(path)

dados.head(5)

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

In [37]:
dados = pd.json_normalize(dados['info_moveis'])

In [38]:
dados.head(3)

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]

Da coluna 3 em diante, percebe que os dados estão em lista?

In [39]:
dados.iloc[1,3]

["Welcome to the heart of the 'Ballard Brewery District'. Walking distance to 7 breweries, as well as the heart of downtown Ballard. Modern, free standing townhome, 3BR, 5 Beds (One King, One Queen, Two Twins, One Full). 2.5 bathrooms. Multiple LED TVs Welcome to the heart of the 'Ballard Brewery District'. Within walking distance to 7 breweries, as well as the heart of downtown Ballard. Modern, free standing townhome with outdoor furniture, as well as a two Queen and one King bed. 2.5 bathrooms, 6 TVs, and everything else you would need for a stay. Kitchen is fully equipped with granite countertops, as well as anything you would need to cook a full meal, or you could enjoy many of the wonderful restaurants in the area. Less than a two block walk to a bus to downtown Seattle, or hop. House is about 40 minutes north of Seatac Airport, 10 minutes north of downtown Seattle. The master bedroom has a king size bed, second bedroom has a bunkbed with a Full+Twin, as well as a Twin trundle bed t",
 "Great location in Capital Hill, Seattle's hippest and most vibrant neighborhood.  Three-story house, featuring 4 Bedrooms, 3 baths, large living area with a perfect layout for cooking, relaxing in the kitchen bar, living room, or nice outdoor space. This is a very clean place, in an excellent location and great amenities.  There are 4 bedrooms, and sleeps up to 10 people comfortably.  Great living space and great outdoor space (fence in yard with outdoor eating area). On the top floor there is one master with it's own bath, a second bath and second bedroom. Excellent living space on second floor with a spacious kitchen with great bar are for hanging out.  The living room is very cozy if you just want to lounge and watch a movie (or the game).   First floor is two bedrooms and one bath.  Each bedroom includes a bunkbed (Full bed on bottom and single bed on top (twin).   This is a three story home with the living space on the second floor.  All amenities including washer/dryer, dishwashe",
 '5-level, bright & modern loft with 20\' ceilings, views, award-winning green design. All amenities. Room to stretch. Stocked kitchen & pantry. New 50" TV. Luxury master suite. Poker table. Parking. Cable. Great for quiet groups, business, families. Welcome to my 5-story loft located about a little over 1 mile from downtown with easy access to the sights and businesses of Seattle. You have access to all 5 levels making it a great space for co-workers, quiet groups and friends or families traveling together.  I\'m sorry but I do not permit parties at the loft. This is a quiet, residential community and if you book the property then you will be held responsible for all actions in your group including noise violations and unauthorized parties. When you stay as a guest at my loft please remember that you are representing me in this community. This loft is 5 stories tall. Not only do the different levels give guests room to have some space of their own for sleeping, the large & open living are',
 'Built in 2015. Convenient to City - 10 min to downtown by direct bus line on the corner!  Please expand "Description" and "House Rules" then read them carefully for early check-in and instant booking! This is listing for entire single family home - 1821sqft plus attached garage. I have one brand-new king size bed with top quality memory form mattress in master room which has a balcony, and two brand-new queen size beds with memory form mattress in another two rooms. If you\'re group is more than 10 people, please consider renting the next door as well.(Please inquire first) 10 seconds by walk: https://www.airbnb.com/rooms/8104742 Equipped with:  - 70" LED TV plus AppleTV for guest use.  - Quartz counter top on cabinets and island.  - Nice wooden 8\' table from Restoration Hardware which can host 8+ people.  - Keurig 2.0 Coffee Brewer. Keeping bunch of K-cups available but it would be great for you if you bring your own favorite K-cups.  - Most-comfortable-ever motorized sectional (has 4 ',
 'Built in 2014. Convenient to City - 10 min to downtown by direct bus line on the corner! Please expand "Description" and "House Rules" then read them carefully. PLEASE NOTE:  As this is recent purchase, the photos here are from real estate. Will update with actual ones soon. Please expect the house is the same but furniture are better and no stickers in the wall. This is listing for entire single family home - 1820sqft plus attached garage. I have one brand-new king size bed with top quality memory form mattress in master room, and two brand-new queen size beds with memory form mattress in another two rooms. If you\'re group is more than 10 people, please consider renting the next door as well.(Please inquire first) 10 seconds by walk: https://www.airbnb.com/rooms/6990882 Equipped with:  - 65" LED TV plus Apple TV for guest use.  - Quartz counter top on cabinets and island.  - Nice modern 8\' table which can host 8+ people.  - Keurig 2.0 Coffee Brewer. Keeping bunch of K-cups available b',
 'This Magnolia townhouse (3 bdrm+loft, 3.5 bath) is centrally located to most Seattle sites (Ballard, Fremont, UW, Cruise terminal, Interbay Golf, Seattle Center, Downtown).  Garage included with Tesla Charger.  Free street parking.  Next to bus line This house was expertly picked because of location, size, and neighborhood amenities. We live 5 minutes away in Magnolia ourselves.  What makes this vacation rental unique compared to other vacation rentals in Seattle: 1. Parking: We have a garage and a driveway to use and there is plenty of free street parking.  Other neighborhoods have paid parking on the streets and no private garage to protect your vehicle.   2. The master bedroom has a staircase to another room above (loft) with access to the deck where you can view Queen Anne.   3. We bought a commercial grade tankless water heater that is capable of supplying unlimited hot water to all the showers (3) in the house and handle the other appliances that require hot water 4. The house is',
 'Fully updated by professional interior designer and all new furnishings.  2 Balconies with View of  Elliot bay and the Space Needle  2 king bedrooms  1 loft queen  1 living-room queen couch bed  1 luxury queen air mattress  2 full baths  Best location! Right in the middle of all the action!  Complete with 2 balconies, pool, gym, sauna, hot tub, 5 blocks from Pikes market and the Space Needle.  A representative will meet you for keys at location includes a quick 5 minute tour of amenities. Only when needed. I love the people, restaurants and excitement in living at this location! Bus, taxi, sedan, train are all within a block. ',
 "Walk to everything West Seattle has to offer- from local bars, restuarants and shopping to the beaches and parks on the water! 4 floor townhome with 3 bedrooms and a loft space. Outdoor spaces include a first floor patio and a 4th floor roof top deck with views of the Puget Sound, islands, Mt Rainier and mountain ranges! Spectacular sunsets! First floor is a flex space/ studio (2 queen beds) with a half bath. This space is connected to the rest of the home but also has a seperate entry if needed. The second floor has the living room (with 2 comfy twin beds that can be pushed together to make a double), open kitchen and half bath. The third floor has 2 bedrooms and a full bath. (Master with queen mattress and 2nd bedroom with a queen air mattress) The fourth floor has a loft/ office and a roof top deck with amazing views! Whole house. The only spaces off limits are the master closet (it will be locked) and the liquor cabinet. Feel free to call, txt, email. 'The Junction' at West Seattle",
 "With its three bedrooms, two kitchens and two living spaces, this modern cottage is perfect for a large family or for groups traveling together. Nestled in the vibrant neighborhood of West Seattle, it offers quick & easy access to downtown Seattle! This charming 1910 cottage has been remodeled into a three-bedroom, two-kitchen, two-bathroom home with a light-filled sun room and lots of modern amenities. It's situated in an ideal location -- just a few minute's drive to downtown Seattle while also a short walk to all the shops and restaurants in the vibrant West Seattle Junction neighborhood. TWO LIVING SPACES - The cottage has two levels - The Main Floor and the Downstairs Basement Apartment. Each level has its own kitchen, bathroom, and bedrooms, and each has its own entrance. This makes the cottage ideal for groups traveling together or for big families who need extra space.  THE MAIN FLOOR: KITCHEN: For those who enjoy cooking, an open kitchen with high-end appliances awaits. The sp",
 "Make this your family home away from home with space for a large groups. If you are you coming to Seattle for business or just for fun and  need the feel of a home rather than a crowded hotel or motel room.  And want to save money on resident for your family, friends or work group stay  at Seattle Sleepy on North Beacon Hill.  We are offering you an 1800 sq foot, beautifully furnished, Mid Century home. It is located in Seattle's North Beacon Hill area. The only thing that our guests will need to make themselves at home is their toothbrush and suitcase.  We are looking forward to hosting you. Guest has access to full house. That includes  four large bedrooms; one bedroom downstairs with a double bed, and on the main floor there are three bedrooms with queen size beds. The home has two bathrooms  which includes all towels and misc bath products. The kitchen is located just next to the dining room and has a small breakfast bar of its own. The kitchen is fully equipped with major applianc",
 "Bright and funky architectural home (Wendell Lovett) with hip furnishings on a wooded property steps away from Lifeguarded Matthews Beach and the Burke-Gilman trail that connects to University of Washington, Children's Hospital, & University Village Shopping Center.  The home is ideal for visiting professors, doctors, or technology & biotech workers because of its proximity to these job centers. Three Bedrooms, 2.5 bathrooms, and Bonus Sleeping Loft.  The main floor is an open plan space looking out onto the views and up into a vaulted ceiling.  The open stairwell is a beautiful architectural feature  For safety purposes, young children will need assistance going up and down them. Guests have access to plenty of parking, a large wooded lot, and two blocks from a bus line that connects to destinations throughout Seattle. We live next door and are available to greet guests, give them the keys, and give them a tour of the home and property.  We also have many suggestions on things to do f"]

Neste exemplo, é interessante explodir essa lista, para que visualizemos todo o conteúdo dela

In [40]:
colunas = list(dados.columns)
colunas[:4]

['avaliacao_geral', 'experiencia_local', 'max_hospedes', 'descricao_local']

In [41]:
dados = dados.explode(colunas[3:])
dados.head(3)

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00

Perceba que o index das linhas está bagunçado, afinal o que era uma linha só, transformou-se em várias linhas que herdaram o index da linha "mãe"

In [42]:
dados.reset_index(inplace=True, drop=True)
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

Show, agora precisamos ver a tipagem das colunas. veja:

In [43]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   str
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   str
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   str
 6   quantidade_quartos    3818 non-null   str
 7   quantidade_camas      3818 non-null   str
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   str
dtypes: str(13)
memory usage: 387.9 KB

max_hospedes, que é uma coluna numérica, está formatada como texto. precisamos concertar todos os casos assim.

In [44]:
dados['max_hospedes'] = dados['max_hospedes'].astype('int64')

In [45]:
colunas_numericas = ['quantidade_banheiros', 'quantidade_camas', 'quantidade_quartos']

dados[colunas_numericas] = dados[colunas_numericas].astype('int64')
dados['avaliacao_geral'] = dados['avaliacao_geral'].astype('float64')

dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   str
dtypes: float64(1), int64(4), str(8)
memory usage: 387.9 KB

Você vai perceber que as vezes é necessário tratar colunas de numeros que contenham letra. veja o caso da coluna preco

In [46]:
dados['preco'].head()

0    $110.00
1     $45.00
2     $55.00
3     $52.00
4     $85.00
Name: preco, dtype: str

É necessário retirar o "$" e as vírgulas que podem aparecer.

In [47]:
dados['preco'] = dados['preco'].apply(lambda x: x.replace('$', '').replace(',', '').strip())

In [48]:
dados['preco'].head()

0    110.00
1     45.00
2     55.00
3     52.00
4     85.00
Name: preco, dtype: str

In [49]:
dados['preco'] = dados['preco'].astype('float64')